version: '3.4'

services:
  nlwexpertjava:
    image: nlwexpertjava
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      JAVA_OPTS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005,quiet=y
    ports:
      - 5434:5434
      - 5005:5005
